flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdatePasswordForm
from ..models import User, Wordle

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("wordles.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))

    return render_template(
        "register.html",  
        form=form,
        title="Register"
    )


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("wordles.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("wordles.index"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template(
        "login.html", 
        form=form,
        title="Login"
    )


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("wordles.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_password_form = UpdatePasswordForm()

    if update_password_form.validate_on_submit():

        if bcrypt.check_password_hash(
            current_user.password, update_password_form.current_password.data
        ):
            hashed_new = bcrypt.generate_password_hash(update_password_form.new_password.data).decode("utf-8")
            current_user.modify(password=hashed_new)
            current_user.save()
            flash("Password updated!")
        else:
            flash("Please re-enter your current password.")
    
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        update_password_form=update_password_form,
        title="Account"
    )

flask_app/wordles/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, abort
from flask_login import current_user, login_required

from ..forms import SearchForm, WordleManualForm, WordlePasteForm
from ..models import User, Wordle
from ..utils import current_time, parse_pasted_wordle, todays_wordle, generate_figure

wordles = Blueprint("wordles", __name__)

@wordles.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("wordles.wordle_detail", wordle_day=form.search_query.data))

    submissions = Wordle.objects()

    if len(submissions) == 0:
        fig = None
    else:
        fig = generate_figure(submissions)

    return render_template(
        "index.html", 
        form=form,
        todays_wordle=todays_wordle(),
        fig=fig
    )

@wordles.route("/submit", methods=["GET", "POST"])
@login_required
def submit_wordle():
    paste_form = WordlePasteForm()
    manual_form = WordleManualForm()
    user = User.objects(username=current_user.username).first()

    # pasted
    if paste_form.text.data and paste_form.validate_on_submit():
        text = paste_form.text.data
        data = parse_pasted_wordle(text)

        if data is not None:
            wordle = Wordle.objects(wordle_day=data["day"], user=user).first()

            if wordle is None:
                new_wordle = Wordle(
                    user=current_user._get_current_object(),
                    grid=data["grid"], 
                    date=current_time(), 
                    wordle_day=data["day"], 
                    guesses=data["guesses"]
                )
                new_wordle.save()
            else:
                wordle.modify(
                    grid=data["grid"], 
                    date=current_time(), 
                    wordle_day=data["day"], 
                    guesses=data["guesses"]
                )
                wordle.save()

            return redirect(url_for("wordles.submit_wordle"))
        else:
            flash("Invalid Wordle data!")
    
    # manual
    if manual_form.wordle_day.data and manual_form.guesses.data and manual_form.validate_on_submit():
        wordle = Wordle.objects(wordle_day=manual_form.wordle_day.data, user=user).first()

        if wordle is None:
            new_wordle = Wordle(
                user=current_user._get_current_object(),
                grid="No grid data",
                date=current_time(), 
                wordle_day=manual_form.wordle_day.data,
                guesses=manual_form.guesses.data
            )
            new_wordle.save()
        else:
            wordle.modify(
                grid="No grid data",
                date=current_time(), 
                wordle_day=manual_form.wordle_day.data,
                guesses=manual_form.guesses.data
            )
            wordle.save()
        
        return redirect(url_for("wordles.submit_wordle"))

    return render_template(
        "submit.html",
        paste_form=paste_form,
        manual_form=manual_form,
        title="Submit Wordle"
    )


@wordles.route("/wordle/<wordle_day>", methods=["GET"])
def wordle_detail(wordle_day):
    if int(wordle_day) < 1:
        return render_template(
            "wordle_detail.html",
            error="Invalid Wordle day"
        )

    submissions = Wordle.objects(wordle_day=wordle_day)

    if len(submissions) == 0:
        fig = None
    else:
        fig = generate_figure(submissions)

    return render_template(
        "wordle_detail.html",
        wordle_day=wordle_day,
        submissions=submissions,
        fig=fig,
        title="Wordle " + wordle_day
    )


@wordles.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    if user is not None:
        submissions = Wordle.objects(user=user).order_by("-wordle_day")

        if len(submissions) == 0:
            fig = None
        else:
            fig = generate_figure(submissions)

        return render_template(
            "user_detail.html", 
            username=username,
            submissions=submissions,
            fig=fig,
            title=username + "\'s Profile"
        )
    else:
        return render_template(
            "user_detail.html", 
            error="User does not exist",
        )

@wordles.route("/about")
def about():
    return render_template(
        "about.html",
        title="About Statdle"
    )

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}

<div class="row mt-3">
    <div class="col text-center">
        <h1>
            About Statdle
        </h1>
        <p>
            Need a dedicated place to archive your Wordle games? Want to see how other people performed on
            that tough Wordle day? Looking to show off your impressive guess distribution? Statdle is the
            site for you! Submit Wordles, view guess distributions globally or for specific Wordle days and
            users, and see your and other users' past Wordle games.
        </p>
        <p>
            This site was built by Alexis Feng with Flask, Jinja, Bootstrap, and MongoDB for CMSC388J. 
            The figures for Wordle statistics are generated with Matplotlib.
        </p>
    </div>
</div>

{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row mt-3">
    <div class="col text-center">
        <h1>Hello, {{ current_user.username }}.</h1>
    </div>
</div>
<div class="row mt-3">
    <div class="col text-center">
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <h3>Change your password</h3>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ update_password_form.csrf_token }}
            <div class="form-group">
                {{ update_password_form.current_password.label(class="form-control-label") }}
                {{ update_password_form.current_password(class="form-control form-control-lg") }}

                {{ update_password_form.new_password.label(class="form-control-label") }}
                {{ update_password_form.new_password(class="form-control form-control-lg") }}

                {% if update_password_form.new_password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in update_password_form.new_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ update_password_form.confirm_password.label(class="form-control-label") }}
                {{ update_password_form.confirm_password(class="form-control form-control-lg") }}

                {% if update_password_form.confirm_password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in update_password_form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ update_password_form.submit }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Statdle</title>
    {% endif %}
</head>
<body>
    {% block header %}
        <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{{ url_for('wordles.index') }}">Statdle</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('wordles.about') }}">
                    About
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('wordles.submit_wordle') }}">
                    Submit Wordle
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ 
                    url_for('wordles.user_detail', username=current_user.username,) 
                }}">
                    Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row mt-3">
    <div class="col text-center">
        {% if current_user.is_authenticated %}
            <h1>Welcome to Statdle, {{ current_user.username }}!</h1>
        {% else %}
            <h1>Welcome to Statdle!</h1>
        {% endif %}
        Submit Wordle games, view stats for a Wordle day, or view stats for a user.
    </div>
</div>
<div class="row mt-5">
    <div class="col text-center">
        <h3><a href="{{ url_for('wordles.wordle_detail', wordle_day=todays_wordle) }}">
            View Today's Wordle - {{ todays_wordle }}
        </a></h3>
    </div>
</div>
<div class="row mt-3">
    <div class="col d-flex justify-content-center sm-2">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Day") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>

{% if fig %}
    <div class="row mt-5">
        <div class="col text-center">
            <h5>Global Guess Distribution</h5>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <img src="data:image/png;charset=utf-8;base64,{{ fig }}" class="responsive">
        </div>
    </div>
{% endif %}

{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row mt-3">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        Don't have an account? <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row mt-3">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        Have an account? <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row mt-3">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/submit.html
{% extends "header.html" %}
{% block content %}

<div class="row mt-3">
    <div class="col-sm-6">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <h2>Paste the results of your Wordle game...</h2>

        <div class="form-group">
            <form action="" method="post">
                {{ paste_form.csrf_token }}
                {{ paste_form.text(class="form-control", rows="8") }}

                {% if paste_form.text.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in paste_form.text.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ paste_form.submit(class="btn btn-outline-success") }}
            </form>
        </div>
    </div>
    <div class="col-sm-6">
        <h2>... or enter in the Wordle day and number of guesses</h2>

        <div class="form-group">
            <form action="" method="post">
                {{ manual_form.csrf_token }}
                {{ manual_form.wordle_day.label(class="form-control-label") }}
                {{ manual_form.wordle_day(class="form-control") }}

                {% if manual_form.wordle_day.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in manual_form.wordle_day.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ manual_form.guesses.label(class="form-control-label") }}
                {{ manual_form.guesses(class="form-control") }}

                {% if manual_form.guesses.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in manual_form.guesses.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ manual_form.submit(class="btn btn-outline-success") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
{% if error %}
    <div class="row mt-3">
        <div class="col text-center">
            <h1>{{ error }}</h1>
            <b><a href="{{ url_for('wordles.index') }}">
                Go back to the home page
            </a></b>
        </div>
    </div>
{% else %}
    <div class="row mt-3">
        <div class="col text-center">
            <h1>{{ username }}'s Wordle Games</h1>
        </div>
    </div>

    {% if fig %}
        <div class="row mt-3">
            <div class="col text-center">
                <h5>Guess Distribution</h5>
            </div>
        </div>
        <div class="row">
            <div class="col text-center">
                <img src="data:image/png;charset=utf-8;base64,{{ fig }}" class="responsive">
            </div>
        </div>
    {% endif %}

    <div class="row mt-3">
        {% if submissions.count() > 0 %}
            <div class="col mb-3">
                <h2> Wordle Games <small class="float-right">{{ submissions.count() }} submissions</small></h2>
                {% for submission in submissions %}
                    <div class="card">
                        <div class="card-header">
                            <span class="float-right">
                                <small>{{ submission.date }}</small>
                            </span>
                            <h5 class="card-title"><a href="{{ url_for('wordles.wordle_detail', wordle_day=submission.wordle_day) }}">
                                Wordle {{ submission.wordle_day }}
                            </a></h5>
                        </div>
                            
                        <div class="card-body">
                            <h6 class="card-subtitle">
                            Wordle {{ submission.wordle_day }}
                            {{ submission.guesses }}/6
                            </h5>

                            <p class="card-text">
                                {% if submission.grid != "No grid data" %}
                                    <pre>{{ submission.grid }}</pre>
                                {% else %}
                                    No grid data!
                                {% endif %}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="col mb-3 text-center">
                {% if current_user.username == username %}
                    <h5>No submissions. 
                    <a href="{{ url_for('wordles.submit_wordle') }}">Submit your first Wordle game!</a></h5>
                {% else %}
                    <h5>No submissions.</h5>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endif %}
{% endblock %}

flask_app/templates/wordle_detail.html
{% extends "header.html" %}
{% block content %}
{% if error %}
    <div class="row mt-3">
        <div class="col text-center">
            <h1>{{ error }}</h1>
            <b><a href="{{ url_for('wordles.index') }}">
                Go back to the home page
            </a></b>
        </div>
    </div>
{% else %}
    <div class="row mt-3">
        {% set day = wordle_day | int %}

        <div class="col text-right my-auto">
            {% if day > 1 %}
            <a href="{{ url_for('wordles.wordle_detail', wordle_day=day-1) }}">
                Previous Day
            </a>
            {% endif %}
        </div>
        <div class="col text-center my-auto">
            <h1>Wordle {{ wordle_day }}</h1>
        </div>
        <div class="col text-left my-auto">
            <a href="{{ url_for('wordles.wordle_detail', wordle_day=day+1) }}">
                Next Day
            </a>
        </div>
    </div>

    {% if fig %}
        <div class="row mt-3">
            <div class="col text-center">
                <h5>Guess Distribution</h5>
            </div>
        </div>
        <div class="row">
            <div class="col text-center">
                <img src="data:image/png;charset=utf-8;base64,{{ fig }}" class="responsive">
            </div>
        </div>
    {% endif %}

    <div class="row mt-3">
        {% if submissions.count() > 0 %}
            <div class="col mb-3">
                <h2> Wordle Games <small class="float-right">{{ submissions.count() }} submissions</small></h2>
                {% if submissions.count() > 2 %}
                    <div class="card-columns mt-3">
                {% else %}
                    <div class="card-deck mt-3">
                {% endif %}
                    {% for submission in submissions %}
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title"><a href="{{ url_for('wordles.user_detail', username=submission.user.username) }}">
                                    @{{ submission.user.username }}
                                </a></h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-subtitle">
                                    Wordle {{ submission.wordle_day }}
                                    {{ submission.guesses }}/6
                                </h5>

                                <p class="card-text">
                                    {% if submission.grid != "No grid data" %}
                                        <pre>{{ submission.grid }}</pre>
                                    {% else %}
                                        No grid data!
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="col mb-3 text-center">
                <h5>No submissions.</h5>
            </div>
        {% endif %}
    </div>
{% endif %}
{% endblock %}